name: Update JSON Data
on:
  schedule:
    - cron: "0 * * * *"   # every hour
  workflow_dispatch:      # allow manual trigger
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate new JSON
        run: |
          echo '{ "time": "'$(date)'"}' > data.json
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data.json
          git commit -m "Update data.json"
          git push
